"""
    Richmond Homeschool Collective

    Student: Oliver Alexanian
    Class: Programming & Automation
    Assignment: Develop a "Rock-Paper-Scissors" game in Python
    Date: October 17, 2021

"""
import random

# Display an announcement to the user welcoming them to the game.

print("Hello! Welcome to the game Rock-Paper-Scissors...")

# Request (and save) input from the user (name and RPS choice).

user_choice = input("Please enter 'r', 'p', or 's': ")

# Determine and display input to be generated by the computer.

choices = ('r', 'p', 's')
computer_choice = choices[random.randint(0, len(choices)-1)]
print("The computer chose", "'", computer_choice, "'")

# Evaluate both inputs collected based on the rules of the RPS game and announce the winner.

"""
'r' > 'p'
'p'>'s'
's'>'r'
"""

y = 'You win!'
c = 'Computer wins!'

if computer_choice == user_choice:
 print ("It is a tie.")
elif computer_choice == 'r' and user_choice == 'p':
 print(y)
elif computer_choice == 'r' and user_choice == 's':
 print(c)
elif computer_choice == 'p' and user_choice == 'r':
 print(c)
elif computer_choice == 'p' and user_choice == 'r':
 print(c)
elif computer_choice == 's' and user_choice == 'r':
 print(y)
elif computer_choice == 's' and user_choice == 'p':
 print(c)

# Ask the user if they would like to play again and accept input. (Restart loop if Y).















