"""
    Richmond Homeschool Collective

    Student: Oliver Alexanian
    Class: Programming & Automation
    Assignment: Develop a "Rock-Paper-Scissors" game in Python
    Date: October 17, 2021

"""
import random

# Display an announcement to the user welcoming them to the game.

print("Hello! Welcome to the game Rock-Paper-Scissors...")

# Request (and save) input from the user (name and RPS choice).

user_choice = input("Please enter 'r', 'p', or 's':")

# Determine and display input to be generated by the computer.
choices = ('r', 'p', 's')
computer_choice = choices[random.randint(0, len(choices)-1)]
print("The computer chose", "'", computer_choice, "'")
print(choice [0])
# Evaluate both inputs collected based on the rules of the RPS game and announce the winner.
if computer_choice == user_choice:
 print ("It is a tie.")
elif computer_choice == 'r' and user_choice == 'p':
 print ("you win!")
elif computer_choice == 'r' and user_choice == 's':
 print("the computer wins")
elif computer_choice == 'p' and user_choice == 'r':
 print ("the computer wins")
elif computer_choice == 'p' and user_choice == 'r':
 print("the computer wins")
elif computer_choice == 's' and user_choice == 'r':
 print("you win!")
elif computer_choice == 's' and user_choice == 'p':
 print("the computer wins")

# Ask the user if they would like to play again and accept input. (Restart loop if Y).















