"""
    Richmond Homeschool Collective

    Student: Oliver Alexanian
    Class: Programming & Automation
    Assignment: Develop a "Rock-Paper-Scissors" game in Python
    Date: October 17, 2021

"""


# Display an announcement to the user welcoming them to the game.



# Request (and save) input from the user (name and RPS choice).



# Determine and display input to be generated by the computer.



# Evaluate both inputs collected based on the rules of the RPS game.


# Display message about who won (user or computer).


# Ask the user if they would like to play again and accept input. (Restart loop if Y).















